### ISSUE TITLE
Problem with latest Docker Image

### ISSUE THREAD

**Issue by fabolhak** [lapicidae/vdr-server#14]
Hello,
I just noticed that the current latest image from Docker Hub does not start correctly.  When I try to run it with `docker run lapicidae/vdr-server` no output is shown. It seems to be stuck at bootup or something.

Digest:sha256:`20828ed08552107fd96cff0d8276e4294dbd8a8eeb7f2647b358079f664bb39c`

**Comment by Borgal77** [comment]
The same here

**Comment by lapicidae** [comment]
Should be fixed with 2e7fb5366fff7a36b88997c6be388ab5d683b478... new build is underway!
The problem was (or is) that the automatic creation of the image (via github action) does not stop if something goes wrong during the creation of AUR packages. In this case it was the "source file integrity check" of the live plugin.

As a workaround I have deactivated the source file check.
I will have to take a closer look at the build process in the near future, but for now it should work like this.

**Comment by Borgal77** [comment]
It works, thanks.

**Comment by fabolhak** [comment]
thanks. Works for me :)
