### ISSUE TITLE
Plugin Robotv

### ISSUE THREAD

**Issue by nolimitek** [lapicidae/vdr-server#4]
Is it possible to add the Robotv Plugin?
https://github.com/pipelka/vdr-plugin-robotv

Thx and best regards
Chris

**Comment by lapicidae** [comment]
Theoretically, you can do this yourself by creating your own [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD).  
Then proceed as described [here](https://github.com/lapicidae/vdr-server/blob/master/build/base/etc/PKGBUILD.d/README.md).  
You can find many suggestions in the [VDR4Arch](https://github.com/VDR4Arch) GitHub repository.  
If you are successful then please share the PKGBUILD with us and possibly also with the plugin author.  

Maybe I'll have a look at it myself, since roboTV seems to be an interesting plugin. However, I lack the time right now.

P.S.  
Revising the pkgbuild tutorial is on my ToDo list

**Comment by nolimitek** [comment]
Thx for your reply. My Problem is i am a complete noob in arch. I already tried to build a pkgbuild but with no success. Can you explain me how top do that

Thx Chris

**Comment by lapicidae** [comment]
You could also ask the VDR4Arch team if they would include roboTV.

I am also not skilled in creating PKGBUILDs, however [this](https://itsfoss.com/create-pkgbuild/) tutorial seems to be a good introduction... and of course the [Arch wiki](https://wiki.archlinux.org/title/PKGBUILD).
In the [VDR4Arch](https://github.com/VDR4Arch/vdr4arch/tree/master/plugins) git you can examine a lot of PKGBUILDs and get inspired.

**Comment by lapicidae** [comment]
I have created a working PKGBUILD.
Please unpack into the directory "vdr/pkgbuild" and then start the container. (don't forget to publish port 34892)

I will also take care of a simple web server so that the channel logos (picons) can be used in RoboTV.

Download:
[vdr-robotv.tar.gz](https://github.com/lapicidae/vdr-server/files/8039527/vdr-robotv.tar.gz)

**Comment by lapicidae** [comment]
Simple picons & epgimages server added -> [c3ed371](https://github.com/lapicidae/vdr-server/commit/c3ed371dc608bf8b25c1eacc0362735eefe94d8b)

new Image is on [dockerhub](https://hub.docker.com/repository/docker/lapicidae/vdr-server)

**Comment by nolimitek** [comment]
I have tested it. But there is a problem with the plugin. If you add a recording over the live plugin the robotv app disconnects every 4 seconds. 

regards Chris

**Comment by lapicidae** [comment]
I get one short disconnection after each timer action.

I also saw your issue description in the roboTV git and will create some logs soon and add them there.

**Comment by nolimitek** [comment]
That would be nice because i find no logs

Thx

**Comment by nolimitek** [comment]
Hi, 

The plugin robotv can not be build anymore
copy to build dir...

build package...

==> Making package: vdr-robotv 0.15.0-1 (Mi 23 Feb 2022 16:36:06 CET)

==> Checking runtime dependencies...

==> Installing missing dependencies...

error: target not found: vdr-api=2.6.0

==> ERROR: 'pacman' failed to install missing dependencies.

==> Missing dependencies:

  -> vdr-api=2.6.0

==> Checking buildtime dependencies...

==> ERROR: Could not resolve all dependencies.

Reassign permissions: /etc/PKGBUILD.d

Reassign permissions: /etc/vdr

Reassign permissions: /srv/vdr/video

Reassign permissions: /var/cache/vdr

Reassign permissions: /var/lib/vdr

Reassign permissions: /vdr/channellogos

Reassign permissions: /vdr/timeshift

Reassign permissions: /vdr/log

regards
Chris

**Comment by lapicidae** [comment]
Try this:
[vdr-robotv.tar.gz](https://github.com/lapicidae/vdr-server/files/8125671/vdr-robotv.tar.gz)

**Comment by nolimitek** [comment]
same failure

==> Making package: vdr-robotv 0.15.0-1 (Mi 23 Feb 2022 16:52:26 CET)

==> Checking runtime dependencies...

==> Installing missing dependencies...

error: target not found: vdr-api=2.6.0

==> ERROR: 'pacman' failed to install missing dependencies.

==> Missing dependencies:

  -> vdr-api=2.6.0

==> Checking buildtime dependencies...

==> ERROR: Could not resolve all dependencies

**Comment by lapicidae** [comment]
Weird...
change in PKGBUILD:

```
depends=('gcc-libs' "vdr-api>=${_vdrapi}")  
to  
depends=('gcc-libs')  
```

This should work, but I will have to check later if the pseudo package "vdr-api" is not installed by default.

**Comment by nolimitek** [comment]
> I get one short disconnection after each timer action.
> 
> I also saw your issue description in the roboTV git and will create some logs soon and add them there.

Do you have already some logs about the failure . And do you use the robotv plugin by yourself ?

regards Chris

**Comment by nolimitek** [comment]
Is Robotv now implemented in your docker image ??

**Comment by lapicidae** [comment]
Should have been done by the VDR4Arch team.
See VDR4Arch/vdr4arch#247 (pull request "Add vdr-robotv")
